// convex/ai/registry.ts

export type AiFunction =
  | "sendMessageToAI"
  | "regenerateResponse"
  | "summarizeText"
  | "generateFlashcards"
  | "generateQuestions"
  | "suggestTags"
  | "explainTopic"
  | "generateMnemonics"
  | "generateStudyPlan"
  | "deepthink"
  | "searchWeb"
  | "getReferences"
  | "analyzeImage"
  | "analyzeDocument"
  | "transcribeAudio"
  | "generateExamQuestions"
  | "autoGradeEssay"
  | "logFeedback"
  | "getChatHistory"
  | "saveConversation"
  | "getConversations"
  | "deleteConversation";

export const AI_REGISTRY: Record<AiFunction, string[]> = {
  sendMessageToAI: [
    "DeepSeek V3",
    "Gemini Flash",
    "GPT-5 Mini",
    "Claude Sonnet 4",
    "Grok 4",
    "DeepSeek Chat",
    "Gemini Flash Lite",
    "GPT-5",
    "Claude Opus 4",
    "Gemini Pro",
    "GPT o3",
    "DeepSeek R1",
    "Grok Mini",
    "Gemini Flash Thinking",
    "Claude Sonnet Thinking",
    "Gemini Pro Deep Think",
    "Claude Opus Thinking",
    "GPT-5 Nano",
    "GPT-5 Pro",
    "Grok Fast",
    "Grok 4 Heavy",
    "DeepSeek R1 Distill",
    "Claude Haiku 4",
    "DeepSeek Coder V2",
    "Grok Code",
  ],
  regenerateResponse: [
    "DeepSeek V3",
    "Gemini Flash",
    "GPT-5 Mini",
    "Claude Sonnet 4",
    "Grok 4",
    "DeepSeek Chat",
    "Gemini Flash Lite",
    "GPT-5",
    "Claude Opus 4",
    "Gemini Pro",
    "GPT o3",
    "DeepSeek R1",
    "Grok Mini",
    "Gemini Flash Thinking",
    "Claude Sonnet Thinking",
    "Gemini Pro Deep Think",
    "Claude Opus Thinking",
    "GPT-5 Nano",
    "GPT-5 Pro",
    "Grok Fast",
    "Grok 4 Heavy",
    "DeepSeek R1 Distill",
    "Claude Haiku 4",
    "DeepSeek Coder V2",
    "Grok Code",
  ],
  summarizeText: [
    "Gemini Flash Lite",
    "DeepSeek Chat",
    "GPT-5 Nano",
    "Claude Haiku 4",
    "Grok Fast",
    "Gemini Flash",
    "GPT-5 Mini",
    "DeepSeek V3",
    "Claude Sonnet 4",
    "Grok Mini",
    "Gemini Flash Thinking",
    "GPT-5",
    "Claude Opus 4",
    "Gemini Pro",
    "DeepSeek R1",
    "Grok 4",
    "GPT o3",
    "Gemini Pro Deep Think",
    "Claude Sonnet Thinking",
    "Claude Opus Thinking",
    "Grok 4 Heavy",
    "DeepSeek R1 Distill",
    "DeepSeek Coder V2",
    "GPT-5 Pro",
    "Grok Code",
  ],
  generateFlashcards: [
    "Gemini Flash",
    "DeepSeek Chat",
    "GPT-5 Mini",
    "Claude Haiku 4",
    "DeepSeek V3",
    "Gemini Flash Lite",
    "Claude Sonnet 4",
    "GPT-5",
    "Gemini Pro",
    "DeepSeek R1",
    "GPT o3",
    "Claude Opus 4",
    "Gemini Flash Thinking",
    "Grok Mini",
    "Grok 4",
    "Claude Sonnet Thinking",
    "Gemini Pro Deep Think",
    "Claude Opus Thinking",
    "GPT-5 Nano",
    "Grok Fast",
    "Grok 4 Heavy",
    "DeepSeek R1 Distill",
    "GPT-5 Pro",
    "DeepSeek Coder V2",
    "Grok Code",
  ],
  generateQuestions: [
    "DeepSeek R1",
    "GPT o3",
    "Claude Opus 4",
    "Gemini Pro Deep Think",
    "GPT-5",
    "Claude Sonnet Thinking",
    "DeepSeek V3",
    "Gemini Pro",
    "Claude Sonnet 4",
    "Grok 4 Heavy",
    "Gemini Flash Thinking",
    "GPT-5 Mini",
    "DeepSeek Chat",
    "Gemini Flash",
    "Grok 4",
    "Claude Haiku 4",
    "GPT-5 Nano",
    "Gemini Flash Lite",
    "Grok Mini",
    "Grok Fast",
    "Claude Opus Thinking",
    "DeepSeek R1 Distill",
    "GPT-5 Pro",
    "DeepSeek Coder V2",
    "Grok Code",
  ],
  suggestTags: [
    "Gemini Flash Lite",
    "GPT-5 Nano",
    "DeepSeek Chat",
    "Claude Haiku 4",
    "Grok Fast",
    "Gemini Flash",
    "GPT-5 Mini",
    "DeepSeek V3",
    "Grok Mini",
    "Claude Sonnet 4",
    "Gemini Flash Thinking",
    "GPT-5",
    "Gemini Pro",
    "Claude Opus 4",
    "DeepSeek R1",
    "Grok 4",
    "GPT o3",
    "Gemini Pro Deep Think",
    "Claude Sonnet Thinking",
    "Claude Opus Thinking",
    "Grok 4 Heavy",
    "DeepSeek R1 Distill",
    "GPT-5 Pro",
    "DeepSeek Coder V2",
    "Grok Code",
  ],
  explainTopic: [
    "Claude Opus 4",
    "GPT-5",
    "DeepSeek R1",
    "Gemini Pro",
    "GPT o3",
    "Claude Sonnet Thinking",
    "Gemini Pro Deep Think",
    "DeepSeek V3",
    "Claude Sonnet 4",
    "Gemini Flash Thinking",
    "Grok 4 Heavy",
    "Grok 4",
    "GPT-5 Mini",
    "DeepSeek Chat",
    "Gemini Flash",
    "Claude Haiku 4",
    "GPT-5 Nano",
    "Gemini Flash Lite",
    "Grok Mini",
    "Grok Fast",
    "Claude Opus Thinking",
    "DeepSeek R1 Distill",
    "GPT-5 Pro",
    "DeepSeek Coder V2",
    "Grok Code",
  ],
  generateMnemonics: [
    "Gemini Flash",
    "Claude Sonnet 4",
    "GPT-5 Mini",
    "DeepSeek V3",
    "Claude Haiku 4",
    "Gemini Flash Lite",
    "GPT-5",
    "DeepSeek Chat",
    "Grok 4",
    "Gemini Flash Thinking",
    "Claude Opus 4",
    "GPT o3",
    "Gemini Pro",
    "DeepSeek R1",
    "Grok Mini",
    "Claude Sonnet Thinking",
    "Gemini Pro Deep Think",
    "Claude Opus Thinking",
    "GPT-5 Nano",
    "Grok Fast",
    "Grok 4 Heavy",
    "DeepSeek R1 Distill",
    "GPT-5 Pro",
    "DeepSeek Coder V2",
    "Grok Code",
  ],
  generateStudyPlan: [
    "DeepSeek V3",
    "GPT-5",
    "Claude Sonnet 4",
    "Gemini Pro",
    "GPT o3",
    "DeepSeek R1",
    "Claude Opus 4",
    "Gemini Flash",
    "DeepSeek Chat",
    "GPT-5 Mini",
    "Gemini Flash Thinking",
    "Claude Sonnet Thinking",
    "Gemini Pro Deep Think",
    "Grok 4",
    "Claude Haiku 4",
    "Gemini Flash Lite",
    "GPT-5 Nano",
    "Grok Mini",
    "Grok Fast",
    "Claude Opus Thinking",
    "Grok 4 Heavy",
    "DeepSeek R1 Distill",
    "GPT-5 Pro",
    "DeepSeek Coder V2",
    "Grok Code",
  ],
  deepthink: [
    "DeepSeek R1",
    "GPT o3",
    "GPT-5",
    "Claude Opus 4",
    "Gemini Pro Deep Think",
    "Claude Opus Thinking",
    "Claude Sonnet Thinking",
    "Gemini Pro",
    "DeepSeek V3",
    "Grok 4 Heavy",
    "Claude Sonnet 4",
    "Gemini Flash Thinking",
    "Grok 4",
    "GPT-5 Mini",
    "DeepSeek Chat",
    "Gemini Flash",
    "Claude Haiku 4",
    "GPT-5 Nano",
    "Gemini Flash Lite",
    "Grok Mini",
    "Grok Fast",
    "DeepSeek R1 Distill",
    "GPT-5 Pro",
    "DeepSeek Coder V2",
    "Grok Code",
  ],
  searchWeb: [
    "Grok 4",
    "Gemini Pro",
    "GPT-5",
    "Claude Sonnet 4",
    "DeepSeek V3",
    "Gemini Flash",
    "GPT-5 Mini",
    "Grok 4 Heavy",
    "DeepSeek R1",
    "Claude Opus 4",
    "Gemini Pro Deep Think",
    "Claude Sonnet Thinking",
    "Gemini Flash Thinking",
    "DeepSeek Chat",
    "Claude Haiku 4",
    "GPT o3",
    "Gemini Flash Lite",
    "GPT-5 Nano",
    "Grok Mini",
    "Grok Fast",
    "Claude Opus Thinking",
    "DeepSeek R1 Distill",
    "GPT-5 Pro",
    "DeepSeek Coder V2",
    "Grok Code",
  ],
  getReferences: [
    "Claude Opus 4",
    "GPT-5",
    "Gemini Pro",
    "DeepSeek R1",
    "GPT o3",
    "Claude Sonnet Thinking",
    "Gemini Pro Deep Think",
    "Claude Sonnet 4",
    "DeepSeek V3",
    "Grok 4",
    "Gemini Flash Thinking",
    "GPT-5 Mini",
    "Gemini Flash",
    "DeepSeek Chat",
    "Claude Haiku 4",
    "GPT-5 Nano",
    "Gemini Flash Lite",
    "Grok Mini",
    "Grok Fast",
    "Claude Opus Thinking",
    "Grok 4 Heavy",
    "DeepSeek R1 Distill",
    "GPT-5 Pro",
    "DeepSeek Coder V2",
    "Grok Code",
  ],
  analyzeImage: [
    "GPT-5",
    "Gemini Pro",
    "Claude Sonnet 4",
    "Grok 4",
    "Gemini Flash",
    "Claude Opus 4",
    "DeepSeek R1",
    "GPT o3",
    "Gemini Pro Deep Think",
    "Claude Sonnet Thinking",
    "GPT-5 Mini",
    "Gemini Flash Thinking",
    "DeepSeek V3",
    "Grok 4 Heavy",
    "Claude Haiku 4",
    "DeepSeek Chat",
    "Gemini Flash Lite",
    "GPT-5 Nano",
    "Grok Mini",
    "Grok Fast",
    "Claude Opus Thinking",
    "DeepSeek R1 Distill",
    "GPT-5 Pro",
    "DeepSeek Coder V2",
    "Grok Code",
  ],
  analyzeDocument: [
    "Gemini Pro",
    "GPT-5",
    "Claude Opus 4",
    "DeepSeek R1",
    "Gemini Pro Deep Think",
    "GPT o3",
    "Claude Sonnet Thinking",
    "DeepSeek V3",
    "Claude Sonnet 4",
    "Gemini Flash Thinking",
    "GPT-5 Mini",
    "Gemini Flash",
    "DeepSeek Chat",
    "Grok 4",
    "Claude Haiku 4",
    "Gemini Flash Lite",
    "GPT-5 Nano",
    "Grok Mini",
    "Grok Fast",
    "Claude Opus Thinking",
    "Grok 4 Heavy",
    "DeepSeek R1 Distill",
    "GPT-5 Pro",
    "DeepSeek Coder V2",
    "Grok Code",
  ],
  transcribeAudio: [
    "GPT-5",
    "Gemini Flash",
    "Gemini Pro",
    "Claude Sonnet 4",
    "DeepSeek V3",
    "GPT-5 Mini",
    "Gemini Flash Lite",
    "Grok 4",
    "Claude Haiku 4",
    "DeepSeek Chat",
    "GPT o3",
    "DeepSeek R1",
    "Claude Opus 4",
    "Gemini Flash Thinking",
    "Gemini Pro Deep Think",
    "Claude Sonnet Thinking",
    "GPT-5 Nano",
    "Grok Mini",
    "Grok Fast",
    "Claude Opus Thinking",
    "Grok 4 Heavy",
    "DeepSeek R1 Distill",
    "GPT-5 Pro",
    "DeepSeek Coder V2",
    "Grok Code",
  ],
  generateExamQuestions: [
    "DeepSeek R1",
    "GPT o3",
    "Claude Opus 4",
    "GPT-5",
    "Gemini Pro Deep Think",
    "Claude Sonnet Thinking",
    "DeepSeek V3",
    "Gemini Pro",
    "Claude Sonnet 4",
    "Grok 4 Heavy",
    "Gemini Flash Thinking",
    "GPT-5 Mini",
    "DeepSeek Chat",
    "Gemini Flash",
    "Grok 4",
    "Claude Haiku 4",
    "GPT-5 Nano",
    "Gemini Flash Lite",
    "Grok Mini",
    "Grok Fast",
    "Claude Opus Thinking",
    "DeepSeek R1 Distill",
    "GPT-5 Pro",
    "DeepSeek Coder V2",
    "Grok Code",
  ],
  autoGradeEssay: [
    "Claude Opus 4",
    "GPT-5",
    "DeepSeek R1",
    "GPT o3",
    "Gemini Pro",
    "Claude Sonnet Thinking",
    "Gemini Pro Deep Think",
    "Claude Sonnet 4",
    "DeepSeek V3",
    "Grok 4",
    "Gemini Flash Thinking",
    "GPT-5 Mini",
    "Gemini Flash",
    "DeepSeek Chat",
    "Claude Haiku 4",
    "GPT-5 Nano",
    "Gemini Flash Lite",
    "Grok Mini",
    "Grok Fast",
    "Claude Opus Thinking",
    "Grok 4 Heavy",
    "DeepSeek R1 Distill",
    "GPT-5 Pro",
    "DeepSeek Coder V2",
    "Grok Code",
  ],
  // Non‑AI functions – no models needed
  logFeedback: [],
  getChatHistory: [],
  saveConversation: [],
  getConversations: [],
  deleteConversation: [],
};